services:
  artel:
    build: .
    environment:
      - RELOAD=true
    volumes:
      - artel-data:/data
      - ./artel:/app/artel

  archivist:
    build: .
    volumes:
      - ./artel:/app/artel

  mcp:
    build: .
    volumes:
      - ./artel:/app/artel

  mdns:
    build: .
    volumes:
      - ./artel:/app/artel

  watchtower:
    profiles:
      - production
